# Generated by Django 3.1.1 on 2020-11-25 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
        ('core', '0002_authtokentoken'),
    ]

    operations = [
    ]
